require "import"
import "android.widget.*"
import "android.view.*"
import "mods.Chimame_Core"

layout={
  RelativeLayout;
  layout_width="-1";
  background=backgroundc;
  layout_height="-1";

  {
    LinearLayout;
    layout_width="-1";
    layout_height="-1";
    orientation="vertical";

    {
      LinearLayout;
      layout_width="-1";
      layout_height="-2";
      elevation="0";
      background=backgroundc;
      orientation="vertical";
      {
        LinearLayout;
        layout_width="fill";
        layout_height="56dp";
        gravity="center|left";
        {
          LinearLayout;
          orientation="horizontal";
          layout_height="56dp";
          layout_width="56dp";
          gravity="center";
          onClick=function()关闭页面()end;
          {
            ImageView;
            ColorFilter=primaryc;
            src=图标("arrow_back");
            layout_height="32dp";
            layout_width="32dp";
            padding="4dp";
            id="fh";
          };
        };
        {
          TextView;
          textColor=primaryc;
          Typeface=字体("product-Bold");
          text="开放源代码引用";
          paddingLeft="16dp";
          textSize="20sp";
          layout_height="-2";
          layout_width="-2";
        };
      };
    };

    {
      ScrollView;
      layout_width="fill";
      layout_height="fill";
      {
        LinearLayout;
        orientation="vertical";
        layout_width="fill";
        layout_height="fill";
        {
          CardView;
          CardElevation="0dp";
          CardBackgroundColor=卡片边框灰色;
          Radius="8dp";
          layout_width="-1";
          layout_height="-2";
          layout_margin="16dp";
          --    layout_marginTop="20dp";
          onClick=function()
            浏览器打开("https://github.com/MUKAPP/MLua-Handbook")
          end,
          {
            CardView;
            CardElevation="0dp";
            CardBackgroundColor=backgroundc;
            Radius=dp2px(8)-2;
            layout_margin="2px";
            layout_width="-1";
            layout_height="-1";
            {
              LinearLayout;
              orientation="vertical";
              layout_width="fill";
              {
                LinearLayout;
                layout_width="fill";
                background=cardbackc;
                {
                  CircleImageView;
                  src="res/github_black.png";
                  layout_width="32dp";
                  padding="6dp";
                  layout_height="32dp";
                  layout_margin="8dp";
                };
                {
                  TextView;
                  layout_gravity="center";
                  --layout_marginLeft="4dp";
                  text="MLua-Handbook";
                  textColor=primaryc;
                  textSize="15dp";
                  Typeface=字体("product-Bold");
                };
              };
              {
                LinearLayout;
                layout_width="fill";
                {
                  TextView;
                  layout_margin="8dp";
                  textColor=textc;
                  textSize="14dp";
                  Typeface=字体("product");
                  text="此项目为MLua手册1.4.0(140)的完整开源。";
                };
              };
              {
                LinearLayout;
                layout_width="fill";
                {
                  TextView;
                  layout_margin="8dp";
                  textColor=secondaryc;
                  textSize="13dp";
                  Typeface=字体("product-Bold");
                  text="Apache-2.0/MUKAPP";
                };
              };
            };
          };
        };
        {
          CardView;
          CardElevation="0dp";
          CardBackgroundColor=卡片边框灰色;
          Radius="8dp";
          layout_width="-1";
          layout_height="-2";
          layout_margin="16dp";
          --    layout_marginTop="20dp";
          onClick=function()
            浏览器打开("https://github.com/bumptech/glide")
          end,
          {
            CardView;
            CardElevation="0dp";
            CardBackgroundColor=backgroundc;
            Radius=dp2px(8)-2;
            layout_margin="2px";
            layout_width="-1";
            layout_height="-1";
            {
              LinearLayout;
              orientation="vertical";
              layout_width="fill";
              {
                LinearLayout;
                layout_width="fill";
                background=cardbackc;
                {
                  CircleImageView;
                  src="res/github_black.png";
                  layout_width="32dp";
                  padding="6dp";
                  layout_height="32dp";
                  layout_margin="8dp";
                };
                {
                  TextView;
                  layout_gravity="center";
                  --layout_marginLeft="4dp";
                  text="Glide";
                  textColor=primaryc;
                  textSize="15dp";
                  layout_margin="8dp";
                  Typeface=字体("product-Bold");
                };
              };
              {
                LinearLayout;
                layout_width="fill";
                {
                  TextView;
                  layout_margin="8dp";
                  textColor=textc;
                  textSize="14dp";
                  Typeface=字体("product");
                  text="An image loading and caching library for Android focused on smooth scrolling.";
                };
              };
              {
                LinearLayout;
                layout_width="fill";
                {
                  TextView;
                  layout_margin="8dp";
                  textColor=secondaryc;
                  textSize="13dp";
                  Typeface=字体("product-Bold");
                  text="Apache-2.0/bumptech";
                };
              };
            };
          };
        };

        {
          CardView;
          CardElevation="0dp";
          CardBackgroundColor=卡片边框灰色;
          Radius="8dp";
          layout_width="-1";
          layout_height="-2";
          layout_margin="16dp";
          --    layout_marginTop="20dp";
          onClick=function()
            浏览器打开("https://github.com/google/material-design-icons")
          end,
          {
            CardView;
            CardElevation="0dp";
            CardBackgroundColor=backgroundc;
            Radius=dp2px(8)-2;
            layout_margin="2px";
            layout_width="-1";
            layout_height="-1";
            {
              LinearLayout;
              orientation="vertical";
              layout_width="fill";
              {
                LinearLayout;
                layout_width="fill";
                background=cardbackc;
                {
                  CircleImageView;
                  src="res/github_black.png";
                  layout_width="32dp";
                  padding="6dp";
                  layout_height="32dp";
                  layout_margin="8dp";
                };
                {
                  TextView;
                  layout_gravity="center";
                  --layout_marginLeft="4dp";
                  text="Material Design Icons";
                  textColor=primaryc;
                  textSize="15dp";
                  Typeface=字体("product-Bold");
                };
              };
              {
                LinearLayout;
                layout_width="fill";
                {
                  TextView;
                  layout_margin="8dp";
                  textColor=textc;
                  textSize="14dp";
                  Typeface=字体("product");
                  text="    Material design icons is the official icon set from Google. The icons are designed under the material design guidelines.";
                };
              };
              {
                LinearLayout;
                layout_width="fill";
                {
                  TextView;
                  layout_margin="8dp";
                  textColor=secondaryc;
                  textSize="13dp";
                  Typeface=字体("product-Bold");
                  text="Apache-2.0/Google";
                };
              };
            };
          };
        };
        {
          CardView;
          CardElevation="0dp";
          CardBackgroundColor=卡片边框灰色;
          Radius="8dp";
          layout_width="-1";
          layout_height="-2";
          layout_margin="16dp";
          --    layout_marginTop="20dp";
          onClick=function()
            浏览器打开("https://github.com/Baseflow/PhotoView")
          end,
          {
            CardView;
            CardElevation="0dp";
            CardBackgroundColor=backgroundc;
            Radius=dp2px(8)-2;
            layout_margin="2px";
            layout_width="-1";
            layout_height="-1";
            {
              LinearLayout;
              orientation="vertical";
              layout_width="fill";
              {
                LinearLayout;
                layout_width="fill";
                background=cardbackc;
                {
                  CircleImageView;
                  src="res/github_black.png";
                  layout_width="32dp";
                  padding="6dp";
                  layout_height="32dp";
                  layout_margin="8dp";
                };
                {
                  TextView;
                  layout_gravity="center";
                  --layout_marginLeft="4dp";
                  text="PhotoView";
                  textColor=primaryc;
                  textSize="15dp";
                  Typeface=字体("product-Bold");
                };
              };
              {
                LinearLayout;
                layout_width="fill";
                {
                  TextView;
                  layout_margin="8dp";
                  textColor=textc;
                  textSize="14dp";
                  Typeface=字体("product");
                  text="    PhotoView aims to help produce an easily usable implementation of a zooming Android ImageView.";
                };
              };
              {
                LinearLayout;
                layout_width="fill";
                {
                  TextView;
                  layout_margin="8dp";
                  textColor=secondaryc;
                  textSize="13dp";
                  Typeface=字体("product-Bold");
                  text="Apache-2.0/Chris Banes";
                };
              };
            };
          };
        };
        --[
        {
          CardView;
          CardElevation="0dp";
          CardBackgroundColor=卡片边框灰色;
          Radius="8dp";
          layout_width="-1";
          layout_height="-2";
          layout_margin="16dp";
          --    layout_marginTop="20dp";
          onClick=function()
            浏览器打开("https://github.com/nirenr/AndroLua_pro")
          end,
          {
            CardView;
            CardElevation="0dp";
            CardBackgroundColor=backgroundc;
            Radius=dp2px(8)-2;
            layout_margin="2px";
            layout_width="-1";
            layout_height="-1";
            {
              LinearLayout;
              orientation="vertical";
              layout_width="fill";
              {
                LinearLayout;
                layout_width="fill";
                background=cardbackc;
                {
                  CircleImageView;
                  src="res/github_black.png";
                  layout_width="32dp";
                  padding="6dp";
                  layout_height="32dp";
                  layout_margin="8dp";
                };
                {
                  TextView;
                  layout_gravity="center";
                  --layout_marginLeft="4dp";
                  text="AndroLua_pro";
                  textColor=primaryc;
                  textSize="15dp";
                  Typeface=字体("product-Bold");
                };
              };
              {
                LinearLayout;
                layout_width="fill";
                {
                  TextView;
                  layout_margin="8dp";
                  textColor=textc;
                  textSize="14dp";
                  Typeface=字体("product");
                  text="    Lua5.3.3 for android pro";
                };
              };
              {
                LinearLayout;
                layout_width="fill";
                {
                  TextView;
                  layout_margin="8dp";
                  textColor=secondaryc;
                  textSize="13dp";
                  Typeface=字体("product-Bold");
                  text="MIT/nirenr";
                };
              };
            };
          };
        };
        --]]
        {
          CardView;
          CardElevation="0dp";
          CardBackgroundColor=卡片边框灰色;
          Radius="8dp";
          layout_width="-1";
          layout_height="-2";
          layout_margin="16dp";
          --    layout_marginTop="20dp";
          onClick=function()
            浏览器打开("https://github.com/daimajia/AndroidViewAnimations")
          end,
          {
            CardView;
            CardElevation="0dp";
            CardBackgroundColor=backgroundc;
            Radius=dp2px(8)-2;
            layout_margin="2px";
            layout_width="-1";
            layout_height="-1";
            {
              LinearLayout;
              orientation="vertical";
              layout_width="fill";
              {
                LinearLayout;
                layout_width="fill";
                background=cardbackc;
                {
                  CircleImageView;
                  src="res/github_black.png";
                  layout_width="32dp";
                  padding="6dp";
                  layout_height="32dp";
                  layout_margin="8dp";
                };
                {
                  TextView;
                  layout_gravity="center";
                  --layout_marginLeft="4dp";
                  text="AndroidViewAnimations";
                  textColor=primaryc;
                  textSize="15dp";
                  Typeface=字体("product-Bold");
                };
              };
              {
                LinearLayout;
                layout_width="fill";
                {
                  TextView;
                  layout_margin="8dp";
                  textColor=textc;
                  textSize="14dp";
                  Typeface=字体("product");
                  text="Cute view animation collection.";
                };
              };
              {
                LinearLayout;
                layout_width="fill";
                {
                  TextView;
                  layout_margin="8dp";
                  textColor=secondaryc;
                  textSize="13dp";
                  Typeface=字体("product-Bold");
                  text="MIT/daimajia";
                };
              };
            };
          };
        };

        {
          CardView;
          CardElevation="0dp";
          CardBackgroundColor=卡片边框灰色;
          Radius="8dp";
          layout_width="-1";
          layout_height="-2";
          layout_margin="16dp";
          --    layout_marginTop="20dp";
          onClick=function()
            浏览器打开("https://github.com/500px/500px-android-blur")
          end,
          {
            CardView;
            CardElevation="0dp";
            CardBackgroundColor=backgroundc;
            Radius=dp2px(8)-2;
            layout_margin="2px";
            layout_width="-1";
            layout_height="-1";
            {
              LinearLayout;
              orientation="vertical";
              layout_width="fill";
              {
                LinearLayout;
                layout_width="fill";
                background=cardbackc;
                {
                  CircleImageView;
                  src="res/github_black.png";
                  layout_width="32dp";
                  padding="6dp";
                  layout_height="32dp";
                  layout_margin="8dp";
                };
                {
                  TextView;
                  layout_gravity="center";
                  --layout_marginLeft="4dp";
                  text="500px-android-blur";
                  textColor=primaryc;
                  textSize="15dp";
                  Typeface=字体("product-Bold");
                };
              };
              {
                LinearLayout;
                layout_width="fill";
                {
                  TextView;
                  layout_margin="8dp";
                  textColor=textc;
                  textSize="14dp";
                  Typeface=字体("product");
                  text="Android Blurring View";
                };
              };
              {
                LinearLayout;
                layout_width="fill";
                {
                  TextView;
                  layout_margin="8dp";
                  textColor=secondaryc;
                  textSize="13dp";
                  Typeface=字体("product-Bold");
                  text="MIT/500px";
                };
              };
            };
          };
        };

        {
          LinearLayout;
          layout_width="fill";

          layout_height="39dp";
          {
            TextView;
            layout_marginLeft="16dp";
            textColor=secondaryc;
            textSize="13dp";
            layout_gravity="center|left";
            Typeface=字体("product-Bold");
            text="特别致谢：";
          };
          {
            ImageView;
            src="res/openlua_logo.png";
            layout_width="80dp";
            layout_height="31dp";
            layout_margin="4dp";
          };
        };





      };
    };
  };
}
activity.setContentView(loadlayout(layout))

波纹({fh},"圆自适应")